name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - uses: actions/setup-go@v3
      #   with:
      #     go-version: '1.20'

      # - uses: goreleaser/goreleaser-action@v4
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     args: release --rm-dist
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: |
          echo "# difii ${TAG_NAME}" > release.md;
          echo "## Installation" >> release.md;
          echo "~~~bash" >> release.md;
          echo "git clone https://github.com/enuesaa/difii.git -b ${TAG_NAME} --depth 1"  >> release.md;
          echo "cd difii"  >> release.md;
          echo "go build && mv difii /usr/local/bin/difii"  >> release.md;
          echo "~~~" >> release.md;
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          body_path: release.md
  